import { useMemo, useState } from 'react';
import { Asterisk, ArrowRight, ArrowUpRight, Award, BookOpen, Bookmark, Brain, Check, ChevronDown, ChevronRight, Clock3, Coffee, Database, Flame, Layers, Lightbulb, Link2, Laptop, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Sparkles, Target, TrainFront, Workflow } from 'lucide-react';
import { useLearning } from '../context';
import { phases, methods } from '../data/catalog';
import { dateKey, dueCards, getStreak, nextLesson, scheduleReview } from '../lib/learning';
import type { Phase, Week } from '../types';
import { HeroArtwork } from './Visuals';

export function PhaseIcon({ phase, size = 21 }: { phase: Phase; size?: number }) {
  const Icon = ({ brain: Brain, sparkles: Sparkles, link: Link2, workflow: Workflow, database: Database, sliders: SlidersHorizontal, shield: ShieldCheck, award: Award })[phase.icon] || Brain;
  return <Icon size={size} strokeWidth={1.7} />;
}

export function Dashboard() {
  const { progress, content, updateProgress, navigate, openLesson } = useLearning();
  const upcoming = nextLesson(content.weeks, progress);
  const allLessons = content.weeks.flatMap(w => w.lessons);
  const completed = allLessons.filter(l => progress.completed.includes(l.id)).length;
  const percent = Math.round(completed / allLessons.length * 100);
  const cards = dueCards(content.weeks.flatMap(w => w.flashcards), progress);
  const streak = getStreak(progress.activity);
  const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 6 + i); return { key: dateKey(d), label: new Intl.DateTimeFormat('de', { weekday: 'short' }).format(d).slice(0, 2), minutes: progress.activity[dateKey(d)] || 0 }; });
  const weekMinutes = days.reduce((sum, d) => sum + d.minutes, 0);
  const weekPercent = Math.min(100, weekMinutes / progress.profile.goalMinutes * 100);
  const session = progress.profile.sessionMinutes;
  return <>
    <div className="page-heading dashboard-heading"><div><div className="eyebrow"><span className="mini-line" /> DEIN PERSÖNLICHER LERNRAUM</div><h1>{progress.profile.name ? `Schön, dass du da bist, ${progress.profile.name}.` : 'Große Ziele. Kleine Schritte.'}</h1><p className="page-description">Entwickle deine KI-Kompetenz. In deinem Tempo, mit einem klaren Plan.</p></div><div className="date-label"><span className="small-dot" /> DEIN LERNWEG BEGINNT HIER</div></div>
    <div className="dashboard-columns"><div className="dashboard-main">
      <section className="hero-card"><div className="hero-copy"><span className="hero-pill"><Sparkles size={13} /> DEIN WEG ZUM KI-MANAGER</span><h2>Verstehen. Anwenden.<br /><span>Souverän entscheiden.</span></h2><p>Vom ersten Aha-Moment zur eigenen KI-Strategie.<br className="desktop-break" /> 48 Lernwochen Wissen, das dich weiterbringt.</p><button className="btn btn-primary hero-button" onClick={() => upcoming ? openLesson(upcoming.lesson.id) : navigate('exams')}>{completed ? 'Weiterlernen' : 'Meine erste Lektion'}<ArrowUpRight size={17} /></button><div className="hero-foot"><span className="avatar-stack"><i>K</i><i>I</i><i>✦</i></span><span>Dein Ziel. Dein Tempo. Dein Kompass.</span></div></div><div className="hero-illustration"><HeroArtwork /><div className="illustration-label"><span className="small-dot" /> NEUGIER IST DEIN STARTPUNKT</div></div></section>
      <section className="time-section"><div className="section-heading"><h2>Wie viel Zeit hast du gerade?</h2><span className="muted">Jeder Schritt zählt.</span></div><div className="time-options">{[{ m: 5, title: 'Für zwischendurch', sub: 'Ein Konzept. Ein Aha.', icon: TrainFront }, { m: 15, title: 'Eine gute Lernpause', sub: 'Verstehen & ausprobieren.', icon: Coffee }, { m: 45, title: 'Zeit zum Eintauchen', sub: 'Vertiefen & anwenden.', icon: Laptop }].map(({ m, title, sub, icon: Icon }) => <button className={`time-option ${session === m ? 'selected' : ''}`} key={m} onClick={() => updateProgress(p => ({ ...p, profile: { ...p.profile, sessionMinutes: m } }))}><span className="time-icon"><Icon size={21} /></span><span className="time-option-copy"><strong>{m} Minuten</strong><span>{title}</span></span><span className="selection-circle">{session === m && <Check size={11} />}</span><span className="time-hint">{sub}</span></button>)}</div></section>
      <section><div className="section-heading"><h2>Für dich als Nächstes</h2><button className="text-link" onClick={() => navigate('path')}>Zum Lernpfad <ArrowRight size={15} /></button></div><div className="next-grid"><article className="card recommended-card"><div className="card-topline"><span className="badge badge-sage">{upcoming ? `MODUL ${upcoming.week.id} · GRUNDLAGEN & PRAXIS` : 'DEIN FINALE'}</span><span className="lesson-symbol"><BookOpen size={21} /></span></div><h3>{upcoming?.lesson.title || 'Bereit für deinen Abschluss?'}</h3><p>{upcoming?.lesson.summary || 'Prüfe dein Wissen im gesamten Lernpfad und finde deine nächsten Lernziele.'}</p><div className="card-bottom"><span className="meta"><Clock3 size={14} /> {session === 5 ? '5 Min. kompakt' : `${upcoming?.lesson.minutes || 30} Min.`} <span className="meta-divider">·</span> {completed ? 'Dein nächster Schritt' : 'Perfekt zum Starten'}</span><button className="round-button dark" aria-label="Empfohlene Lektion starten" onClick={() => upcoming ? openLesson(upcoming.lesson.id) : navigate('exams')}><ArrowUpRight size={20} /></button></div></article><article className="card recall-card"><div className="card-topline"><span className="badge badge-peach">WISSEN FESTIGEN</span><span className="lesson-symbol peach"><Layers size={21} /></span></div><h3>Einmal gelernt.<br /> Wirklich behalten.</h3><p>{cards.length} Karteikarten warten auf dich. Hol dein Wissen aus dem Gedächtnis zurück.</p><div className="card-bottom"><span className="meta"><RotateCcw size={14} /> Spaced Repetition</span><button className="round-button" aria-label="Karteikarten wiederholen" onClick={() => navigate('studio')}><ArrowUpRight size={20} /></button></div></article></div></section>
      <section className="path-preview"><div className="section-heading"><div><h2>Dein Lernpfad auf einen Blick</h2><p className="section-subtitle">12 Module. 48 Lernwochen. Eine neue Perspektive.</p></div><button className="text-link" onClick={() => navigate('path')}>Alles ansehen <ArrowRight size={15} /></button></div><div className="phase-preview-grid">{phases.slice(0, 4).map(phase => <button className="phase-preview-card" key={phase.id} onClick={() => navigate('path')}><span className={`phase-icon ${phase.color}`}><PhaseIcon phase={phase} /></span><span className="phase-small">MODUL {String(phase.id).padStart(2, '0')}</span><strong>{phase.short}</strong><span className="phase-preview-foot">3 Lektionen <ChevronRight size={14} /></span></button>)}</div></section>
    </div><aside className="dashboard-aside"><section className="card goal-card"><div className="section-heading"><h2>Dein Wochenziel</h2><button className="icon-button" aria-label="Wochenziel anpassen" onClick={() => navigate('settings')}><SlidersHorizontal size={16} /></button></div><div className="goal-ring" style={{ background: `conic-gradient(var(--green) ${weekPercent}%, #edf1e8 0)` }}><div><Target size={22} /><strong>{Math.round(weekMinutes)}<span> / {progress.profile.goalMinutes}</span></strong><span>Minuten gelernt</span></div></div><p className="goal-message">{weekMinutes >= progress.profile.goalMinutes ? 'Ziel erreicht. Nimm dir Zeit, es zu feiern.' : 'Kleine Lernmomente machen den Unterschied.'}</p><div className="streak-row"><span><Flame size={17} /> Dein Lernrhythmus</span><strong>{streak} {streak === 1 ? 'Tag' : 'Tage'}</strong></div><div className="activity-bars">{days.map(d => <div key={d.key}><div className="activity-track"><span style={{ height: `${d.minutes ? Math.max(8, Math.min(100, d.minutes / 45 * 100)) : 0}%` }} /><i className={d.key === dateKey() ? 'today' : ''} /></div><span>{d.label}</span></div>)}</div><div className="activity-legend"><span className="small-dot" /> Deine tatsächliche Lernzeit · letzte 7 Tage</div></section>
      <section className="card overall-card"><div className="section-heading"><h2>Dein Fortschritt</h2><span className="soft-icon"><RouteIcon /></span></div><div className="progress-number">{percent}<span>%</span><span className="muted">des Lernpfads</span></div><div className="progress-track"><span style={{ width: `${percent}%` }} /></div><div className="progress-caption"><span>{completed} von {allLessons.length} Lektionen</span><span>48 Lernwochen</span></div></section>
      <section className="wisdom-card"><span className="wisdom-icon"><Lightbulb size={23} strokeWidth={1.5} /></span><span className="eyebrow">LERNEN, DAS BLEIBT</span><h3>Erklären ist<br />das neue Verstehen.</h3><p>Erkläre jemandem in 60 Sekunden, was du gerade gelernt hast. Ohne Fachwörter. Mit einem Beispiel.</p><button className="text-link" onClick={() => navigate('studio')}>Lernmethoden entdecken <ArrowUpRight size={14} /></button><Asterisk className="wisdom-decoration" size={85} strokeWidth={1} /></section>
      <div className="aside-foot"><ShieldCheck size={14} /><span>Dein Fortschritt bleibt bei dir.<br />Lokal gespeichert. Jederzeit exportierbar.</span></div>
    </aside></div>
  </>;
}

function RouteIcon() { return <BookOpen size={17} />; }

export function PathPage() {
  const { content, progress, openLesson, startExam } = useLearning();
  const [query, setQuery] = useState('');
  const [expanded, setExpanded] = useState<number[]>([nextLesson(content.weeks, progress)?.week.phase || 1]);
  const total = content.weeks.flatMap(w => w.lessons).length;
  const done = content.weeks.flatMap(w => w.lessons).filter(l => progress.completed.includes(l.id)).length;
  const savedLessons = content.weeks.flatMap(w => w.lessons).filter(l => progress.bookmarks.includes(l.id));
  return <><div className="page-heading"><div className="eyebrow">SCHRITT FÜR SCHRITT</div><h1>Dein Weg zum KI-Manager.</h1><p className="page-description">Ein klarer Plan, viel Raum für dein Tempo. Alle Module sind frei zugänglich.</p></div><div className="path-toolbar"><div className="search-field"><Search size={18} /><input aria-label="Lernpfad durchsuchen" placeholder="Themen und Lektionen suchen …" value={query} onChange={e => setQuery(e.target.value)} /></div><span className="badge badge-sage">{done} / {total} Lektionen abgeschlossen</span></div><>{savedLessons.length > 0 && <section className="card bookmark-list"><div className="section-heading"><h2><Bookmark size={16} /> Deine Merkliste</h2><span className="muted">Zum Nachlesen & Vertiefen</span></div><div className="button-row">{savedLessons.map(l => <button className="btn btn-secondary" key={l.id} onClick={() => openLesson(l.id)}><BookOpen size={15} />{l.title}<ArrowRight size={14} /></button>)}</div></section>}</><div className="phase-list">{phases.filter(phase => !query || content.weeks.filter(w => w.phase === phase.id).some(w => `${w.title} ${w.lessons.map(l => l.title).join(' ')}`.toLowerCase().includes(query.toLowerCase()))).map(phase => { const weeks = content.weeks.filter(w => w.phase === phase.id); const lessons = weeks.flatMap(w => w.lessons); const count = lessons.filter(l => progress.completed.includes(l.id)).length; const isOpen = !!query || expanded.includes(phase.id); return <section className="card phase-section" key={phase.id}><button className="phase-header" onClick={() => setExpanded(v => v.includes(phase.id) ? v.filter(id => id !== phase.id) : [...v, phase.id])} aria-expanded={isOpen}><span className={`phase-icon ${phase.color}`}><PhaseIcon phase={phase} size={25} /></span><span className="phase-header-copy"><span className="eyebrow">MODUL {String(phase.id).padStart(2, '0')} · {lessons.length} LEKTIONEN</span><h2>{phase.title}</h2><p>{phase.description}</p></span><span className="phase-count">{count === lessons.length && lessons.length ? <Check size={20} /> : `${count}/${lessons.length}`}</span><ChevronDown className={isOpen ? 'rotated' : ''} size={20} /></button>{isOpen && <div className="week-grid">{weeks.map(week => <WeekCard key={week.id} week={week} openLesson={openLesson} startExam={startExam} completed={progress.completed} />)}</div>}</section>; })}</div>{query && !content.weeks.some(w => `${w.title} ${w.lessons.map(l => l.title).join(' ')}`.toLowerCase().includes(query.toLowerCase())) && <div className="empty-state"><Search /><h3>Kein Thema gefunden</h3><p>Versuche „RAG“, „Agent“ oder „Grundlagen“.</p></div>}</>;
}

function WeekCard({ week, completed, openLesson, startExam }: { week: Week; completed: string[]; openLesson: (id: string) => void; startExam: (scope: string) => void }) {
  return <article className="week-card"><div className="week-label">MODUL {String(week.id).padStart(2, '0')}<span>{week.lessons.filter(l => completed.includes(l.id)).length}/{week.lessons.length}</span></div><h3>{week.title}</h3><p>{week.subtitle}</p><div className="lesson-list">{week.lessons.map((l, i) => <button key={l.id} onClick={() => openLesson(l.id)}><span className={`lesson-number ${completed.includes(l.id) ? 'done' : ''}`}>{completed.includes(l.id) ? <Check size={12} /> : i + 1}</span><span>{l.title}<small>{l.minutes} Min. · Verstehen & anwenden</small></span><ChevronRight size={16} /></button>)}</div><button className="text-link week-quiz" onClick={() => startExam(`week:${week.id}`)}>Wissen dieses Moduls testen <ArrowRight size={14} /></button></article>;
}

export function StudioPage() {
  const { content, progress, updateProgress } = useLearning();
  const [tab, setTab] = useState('cards');
  const [revealed, setRevealed] = useState(false);
  const [reviewed, setReviewed] = useState(0);
  const [selectedWeek, setSelectedWeek] = useState(1);
  const [allCards, setAllCards] = useState(false);
  const [selectedCard, setSelectedCard] = useState(0);
  const [showSample, setShowSample] = useState(false);
  const [query, setQuery] = useState('');
  const cards = content.weeks.flatMap(w => w.flashcards);
  const glossary = content.library?.glossary || [];
  const focus = progress.profile.focus;
  const available = useMemo(() => dueCards(cards, progress), [cards, progress]);
  const reviewCard = allCards ? cards[selectedCard % cards.length] : available[0];
  const week = content.weeks.find(w => w.id === selectedWeek) || content.weeks[0];
  const practice = progress.practice[`week-${week.id}`] || { text: '', checked: [] };
  function rate(grade: 'again' | 'hard' | 'good' | 'easy') {
    if (!reviewCard) return;
    updateProgress(p => ({ ...p, reviews: { ...p.reviews, [reviewCard.id]: scheduleReview(p.reviews[reviewCard.id], grade) } }));
    setRevealed(false); setReviewed(n => n + 1); if (allCards) setSelectedCard(n => n + 1);
  }
  return <><div className="page-heading"><div className="eyebrow">WISSEN WIRD KOMPETENZ</div><h1>Dein Wissensstudio.</h1><p className="page-description">Wiederholen, ausprobieren, laut erklären. Hier bleibt Wissen hängen.</p></div><div className="tab-bar">{[{ id: 'cards', title: 'Karteikarten', icon: Layers }, { id: 'practice', title: 'Praxiswerkstatt', icon: Lightbulb }, { id: 'glossary', title: 'Begriffe entdecken', icon: BookOpen }, { id: 'methods', title: 'Lernmethoden', icon: Brain }].map(({ id, title, icon: Icon }) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => setTab(id)}><Icon size={17} />{title}</button>)}</div>
    {tab === 'cards' && <div className="studio-columns"><section className="card flashcard-section"><div className="section-heading"><h2>{allCards ? 'Alle Begriffe entdecken' : 'Deine Wiederholung'}</h2><span className="badge badge-sage">{reviewed} heute in dieser Sitzung</span></div><p className="muted">Versuche zuerst, die Antwort selbst zu formulieren. Dann decke sie auf.</p>{reviewCard ? <><div className={`flashcard ${revealed ? 'revealed' : ''}`}><span className="eyebrow">MODUL {reviewCard.week} · {revealed ? 'DIE ERKLÄRUNG' : 'DEIN GEDÄCHTNIS IST DRAN'}</span><h2>{reviewCard.front}</h2>{revealed ? <p className="flashcard-answer">{reviewCard.back}</p> : <span className="flashcard-placeholder"><Brain size={32} strokeWidth={1.3} /> Denk kurz nach. Du kannst das.</span>}</div>{!revealed ? <button className="btn btn-primary" onClick={() => setRevealed(true)}>Antwort aufdecken <RotateCcw size={17} /></button> : <div className="review-ratings"><p>Wie gut wusstest du es?</p><div>{[{ id: 'again', label: 'Noch einmal', sub: 'in 10 Min.' }, { id: 'hard', label: 'Schwierig', sub: 'bald wiederholen' }, { id: 'good', label: 'Gewusst', sub: 'Abstand erhöhen' }, { id: 'easy', label: 'Ganz sicher', sub: 'später wiederholen' }].map(x => <button className={`rating-${x.id}`} key={x.id} onClick={() => rate(x.id as 'again' | 'hard' | 'good' | 'easy')}>{x.label}<small>{x.sub}</small></button>)}</div></div>}</> : <div className="empty-state"><Check size={42} /><h3>Für heute gut gefestigt.</h3><p>Gerade sind keine Karten fällig. Neue Begriffe werden nach deiner nächsten Lektion freigeschaltet.</p><button className="btn btn-secondary" onClick={() => { setAllCards(true); setRevealed(false); }}>Alle Begriffe entdecken</button></div>}<button className="text-link card-mode-button" onClick={() => { setAllCards(v => !v); setRevealed(false); }}>{allCards ? 'Zur fälligen Wiederholung' : 'Alle Karten frei üben'} <ArrowRight size={14} /></button></section><aside><section className="card"><span className="phase-icon peach"><Layers size={23} /></span><h3>Abstand statt Auswendiglernen.</h3><p>Je sicherer du eine Karte kennst, desto später kommt sie zurück. Schwierige Begriffe wiederholst du früher.</p><div className="review-stat"><strong>{available.length}</strong><span>aktuell fällige Karten</span></div><div className="review-stat"><strong>{Object.keys(progress.reviews).filter(id => cards.some(c => c.id === id)).length}</strong><span>bereits geübte Begriffe</span></div><p className="fine-print">Modul 1 ist zum Einstieg aktiv. Weitere Karten erscheinen, sobald du eine Lektion des jeweiligen Moduls abschließt.</p></section></aside></div>}
    {tab === 'practice' && <>{focus === 'private' && <div className="callout"><strong>Dein Schwerpunkt: private Anwendung</strong><p>Nutze die privaten Beispiele im Schritt „Anwenden“ jeder Lektion. Die Praxiswerkstatt trainiert zusätzlich die beruflichen Kompetenzen deines KI-Management-Ziels.</p></div>}<div className="practice-toolbar"><label className="field"><span>Deinen Praxisfall auswählen</span><select value={selectedWeek} onChange={e => { setSelectedWeek(Number(e.target.value)); setShowSample(false); }}>{content.weeks.map(w => <option key={w.id} value={w.id}>Modul {w.id}: {w.title}</option>)}</select></label></div><div className="studio-columns"><section className="card practice-card"><span className="badge badge-peach">TRANSFER · MODUL {week.id}</span><h2>{week.challenge.title}</h2><p className="scenario-text">{week.challenge.scenario}</p><div className="callout"><strong>Dein Auftrag</strong><p>{week.challenge.task}</p></div><label className="field"><span>Dein Lösungsentwurf</span><textarea rows={8} maxLength={20000} placeholder="Welche Lösung schlägst du vor – und warum?" value={practice.text} onChange={e => updateProgress(p => ({ ...p, practice: { ...p.practice, [`week-${week.id}`]: { ...practice, text: e.target.value } } }))} /></label><span className="fine-print">Dein Entwurf wird automatisch lokal gespeichert.</span><button className="btn btn-secondary" onClick={() => setShowSample(v => !v)}>{showSample ? 'Musterlösung schließen' : 'Mit Musterlösung vergleichen'}<ChevronDown size={16} /></button>{showSample && <div className="sample-answer"><h3>Ein möglicher Lösungsweg</h3><p>{week.challenge.sample}</p></div>}</section><aside className="card"><span className="phase-icon sage"><Target size={23} /></span><h3>Deine Selbstbewertung</h3><p>Prüfe deinen Entwurf an diesen Kriterien. Es gibt oft mehrere gute Lösungswege.</p><div className="rubric-list">{week.challenge.rubric.map((r, i) => <label key={i}><input type="checkbox" checked={practice.checked.includes(i)} onChange={() => updateProgress(p => ({ ...p, practice: { ...p.practice, [`week-${week.id}`]: { ...practice, checked: practice.checked.includes(i) ? practice.checked.filter(v => v !== i) : [...practice.checked, i] } } }))} /><span>{r}</span></label>)}</div><span className="badge badge-sage">{practice.checked.length} / {week.challenge.rubric.length} Kriterien erfüllt</span><p className="fine-print">Die Bewertung erfolgt durch dich, nicht durch eine KI oder eine offizielle Prüfungsstelle.</p></aside></div></>}
    {tab === 'glossary' && <><div className="search-field"><Search size={18} /><input aria-label="Glossar durchsuchen" value={query} onChange={e => setQuery(e.target.value)} placeholder="z. B. RAG, Token, Governance …" /></div><div className="glossary-grid">{glossary.filter(g => `${g.term} ${g.definition} ${g.example}`.toLowerCase().includes(query.toLowerCase())).map(g => <article className="card glossary-card" key={g.term}><span className="eyebrow">AUS DEINER LERNBIBLIOTHEK</span><h3>{g.term}</h3><p>{g.definition}</p><div className="callout"><strong>Ein Beispiel</strong><p>{g.example}</p></div></article>)}</div>{!glossary.some(g => `${g.term} ${g.definition} ${g.example}`.toLowerCase().includes(query.toLowerCase())) && <div className="empty-state"><Search /><h3>Kein Begriff gefunden.</h3></div>}</>}
    {tab === 'methods' && <div className="method-grid">{methods.map((m, i) => <article className="card" key={m.title}><span className={`phase-icon ${['sage', 'peach', 'blue', 'lilac'][i]}`}>{[<Brain key="b" />, <Layers key="l" />, <Coffee key="c" />, <Lightbulb key="p" />][i]}</span><span className="eyebrow">METHODE {i + 1}</span><h2>{m.title}</h2><p>{m.text}</p><div className="callout"><strong>So nutzt du es hier</strong><p>{['Decke die Karteikartenantwort erst auf, nachdem du selbst geantwortet hast.', 'Bewerte deine Erinnerung ehrlich. Die nächste Wiederholung wird passend geplant.', 'Nutze die 60-Sekunden-Erklärfrage am Ende jeder Lektion. Erkläre sie laut oder als Notiz.', 'Bearbeite den Modulfall in der Praxiswerkstatt und prüfe ihn anhand der Kriterien.'][i]}</p></div></article>)}</div>}
  </>;
}
